version: '3.4'

services:
  redis:
    image: "redis:7.2"
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: unless-stopped

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "sqlserver"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
    ports:
      - "1433:1433"
    volumes:
      - './mssql-data:/var/opt/mssql/data'
    restart: unless-stopped

